### PR TITLE
childprocess: handle errors from uv.spawn

### PR DESCRIPTION
**Pull request by joerg-krause**
`uv.spawn()` might fail and return a `nil` handle and an error message
instead of a `pid`.

`spawn`, `exec`, and `execFile` will now return a `nil` handle and the error
message when `uv.spawn()` fails

Related to: https://github.com/luvit/lit/issues/219

Fixes: #1055

### CODE REVIEW

**Comment by squeek502** [comment]
Looking at the code/tests, was this not handled already?

```lua
  handle, pid = uv.spawn(command, ...)

  em = Process:new(stdin, stdout, stderr)
  em:setHandle(handle)
  em:setPid(pid)

  if not em.handle then
    timer.setImmediate(function()
      em.exitCode = -127
      em:emit('exit', em.exitCode)
      em:emit('error', Error:new(pid))
      if em.stdout then em.stdout:emit('error', Error:new(pid)) end
      if em.stderr then em.stderr:emit('error', Error:new(pid)) end
      if em.stdin then em.stdin:emit('error', Error:new(pid)) end
      maybeClose()
    end)
end
```

```lua
  test('invalid command', function(expect)
    local child, onError

    -- disable on windows, bug in libuv
    if los.type() == 'win32' then return end

    function onError(err)
      assert(err)
    end

    child = spawn('skfjsldkfjskdfjdsklfj')
    child:on('error', expect(onError))
    child.stdout:on('error', expect(onError))
    child.stderr:on('error', expect(onError))
  end)

  test('invalid command verify exit callback', function(expect)
    local child, onExit, onClose

    -- disable on windows, bug in libuv
    if los.type() == 'win32' then return end

    function onExit() p('exit') end
    function onClose() p('close') end

    child = spawn('skfjsldkfjskdfjdsklfj')
    child:on('exit', expect(onExit))
    child:on('close', expect(onClose))
  end)
```

**Comment by joerg-krause** [comment]
Yes, the `error` handler is called after `exec()` returns and after the `exit` handler.

The problem is that `exec()` returns a non-nil `child` and the `pid` of the child is an error message (e.g. `ENOMEM: not enough memory`), whereas I would expect that the child return by `exec()` is `nil`.

**Comment by squeek502** [comment]
Yeah, it's a bit of a weird pattern. I prefer the `nil, err` return style, but it looks like this is setup for the `:on('error', function() end)` pattern exclusively, and changing that to `nil, err` would be a breaking change (and at the very least would need the tests updated). Perhaps as an alternative, the `Process` returned could handle the error case a bit better? For example, [this line](https://github.com/luvit/luvit/blob/455d2f1a41a511f46667180a2570d65bc436f839/deps/childprocess.lua#L151) could instead do something like `if not handle then em:setError(pid) else em:setPid(pid) end`?

By the way, it's very easy to get `uv.spawn()` to return `nil, err` by just giving it an invalid command to run; it will return `ENOENT: no such file or directory`.

**Comment by joerg-krause** [comment]
I agree, I prefer the `nil, err` return style. On the hander hand, `child:on(...)` would need to be guarded by checking `if child then child:on(...) end`.

The real issue here is the lack of documentation. I often need to study the sources to understand how functions should be used.

So, closing this issue as there is nothing really wrong about the error handling, but just a misunderstanding of things actually work.

**Pull request closed without merging**
