### PR TITLE
I added a few examples.

### PR DESCRIPTION
**Pull request by taesoobear**
The examples are ports of some basic node.js tutorials.

### CODE REVIEW

**Comment by Miigon** [comment]
Ugh,I don't think `a` is a good commit message.
A better commit message should contains introdutions about the changes you made.

**Comment by taesoobear** [comment]
I amended the commit message.

**Comment by rphillips** [comment]
this branch should be rebased so the commit message gets changed correctly

**Comment by taesoobear** [comment]
I rebased the branch, and squashed the two commit messages into one.

**Comment by creationix** [comment]
Hmm, it's still showing the other commits.  If you want, I can cherry-pick your commit on top of master.

**Comment by taesoobear** [comment]
Yes, please do so. It seems that I should have not pulled your latest
updates.

2016. 12. 16. 오전 2:34에 "Tim Caswell" <notifications@github.com>님이 작성:

**Comment by creationix** [comment]
Cherry-picked from your repo. https://github.com/luvit/luvit/commit/9fa47b31932e90d8e62fa0a546cf05dab161461f

**Pull request closed without merging**
