### PR TITLE
simplify

### PR DESCRIPTION
**Pull request by zhaozg**
some cherry-pick from https://github.com/zhaozg/luvit/tree/extend

### CODE REVIEW

**Comment by squeek502** [comment]
Will review this tomorrow.

**Comment by zhaozg** [comment]
Sorry a force push on error remote, this PR on master now. @squeek502

**Comment by zhaozg** [comment]
I has create a [branch_protection_rules] (https://github.com/luvit/luvit/settings/branch_protection_rules/15699543),  but that not works for me.  strange

**Comment by rphillips** [comment]
The 'Include administrators' option wasn't checked... I just turned it on.

I pulled a couple days ago... I see some commits on top of master that weren't a PR... Are these intended?

image

**Comment by rphillips** [comment]
First 5 commits.

**Comment by squeek502** [comment]
Those are the commits that were in this PR. I think we should force push master back to `Merge pull request #1111` and then re-submit those commits them as multiple different PRs (since they aren't related).

https://github.com/luvit/luvit/commit/14b62630a1cd9dddccd5b44158453cf05c18c9c2, for example, is a potentially breaking change (since Worker is no longer an Object).

**Comment by rphillips** [comment]
+1

**Comment by squeek502** [comment]
Ok, master has been force pushed to before those 5 commits. @zhaozg, please submit separate PRs for each change.

**Comment by zhaozg** [comment]
Thanks everyone.

**Comment by zhaozg** [comment]
Ok, I split this into other PRs, please check that.

**Pull request closed without merging**
