### PR TITLE
convert test in tests/to-convert 

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by rphillips** [comment]
Thanks for pitching in!

**Comment by zhaozg** [comment]
You are welcome

**Comment by rphillips** [comment]
wow! I'll look this over. Thank you!

**Comment by zhaozg** [comment]
according to https://travis-ci.org/luvit/luvit/builds/60815375#L369-L370, there maybe a bug in fs.statSync, because returned stat.mode is 0, please check over that on linux.

**Comment by zhaozg** [comment]
error at: # Starting Test: fs-truncate - fs truncate
  [string "/home/travis/build/luvit/luvit/tests/test-fs-..."]:34: attempt to index local 'stat' (a nil value)
  stack traceback:
  	[string "/home/travis/build/luvit/luvit/tests/test-fs-..."]:34: in function 'fn'
  	[string "/home/travis/build/luvit/luvit/tests/libs/tap..."]:66: in function <[string "/home/travis/build/luvit/luvit/tests/libs/tap..."]:55>
  	[C]: in function 'xpcall'
  	[string "/home/travis/build/luvit/luvit/tests/libs/tap..."]:55: in function 'run'
  	[string "/home/travis/build/luvit/luvit/tests/libs/tap..."]:151: in function 'tap'
  	[string "/home/travis/build/luvit/luvit/tests/run.lua"]:29: in function 'fn'
  	[string "bundle:deps/require.lua"]:260: in function 'require'
  	[string "bundle:main.lua"]:115: in function 'main'
  	[string "bundle:/init.lua"]:34: in function <[string "bundle:/init.lua"]:32>
  	[C]: in function 'xpcall'
  	[string "bundle:/init.lua"]:32: in function <[string "bundle:/init.lua"]:20>

**Comment by rphillips** [comment]
I fixed up the chmod test:

https://gist.github.com/rphillips/5ab852ebe23a5fb8521f

**Comment by rphillips** [comment]
merged with https://github.com/luvit/luvit/pull/723

**Comment by rphillips** [comment]
Thank you for working on this!

**Pull request merged**
