### PR TITLE
Fix http chunked encoding

### PR DESCRIPTION
**Pull request by gsick**
Hi all,

Fix in http.lua for http methods other than get, head and connect when useChunkedEncodingByDefault is true.
The size calculation was wrong.

### CODE REVIEW

**Comment by creationix** [comment]
Thanks, I guess I've been doing too much JS over the years.

**Comment by gsick** [comment]
Have you planned a minor release soon?

**Comment by creationix** [comment]
I think @rphillips wanted to cut a release soon.

**Comment by rphillips** [comment]
yeah, we need to tag master

**Comment by gsick** [comment]
Ok, nice. Thanks

**Pull request merged**
