### PR TITLE
Release 2.14.1

### PR DESCRIPTION
**Pull request by creationix**
# Changes in 2.14.1

 - dns: Allow ip addresses in dns resolve to resolve internally. [NiteHawk]
 - http-codec: Add HTTP status codes of RFC 6585 [Navid]
 - require: Fix bundle requires on Windows [Squeek]
 - Support punctuation in http credentials [Charles Farquhar]
 - Update lit to 3.5.4 [Tim Caswell]

### CODE REVIEW

**Comment by joerg-krause** [comment]
Any intention to resolve https://github.com/luvit/luvit/issues/950? The agreement was to revert commit https://github.com/luvit/luvit/commit/edf48cf3093a574805595e612680c006a6cdf741.

**Comment by creationix** [comment]
@joerg-krause Good catch, anything else?

**Comment by SinisterRectus** [comment]
Looks good as far as I can tell.

**Comment by creationix** [comment]
Hmm, the repl is broken for me (try ALT + Arrows or Control + Arrows on gnome terminal)  It should be jump word or home/end just like in bash, but instead if crashes.  I suspect it's related to the new ustring code.  I'm going to publish this for now, but we should fix that soon.

**Comment by joerg-krause** [comment]
@creationix Thanks! Nothing else from my point of view.

**Pull request merged**
