### PR TITLE
tls support client session reuse

### PR DESCRIPTION
**Pull request by zhaozg**
This RP make tls support client session resuse, and need update lua-openssl to newest master branch of https://github.com/zhaozg/lua-openssl.

Please review this PR should be accept?
to get better performance TLSSocket should use shared secureContext, eg: 
secureContext = tls.createCredentials(...) --to share will multi TLSSocket,
tls.connect({secureContext = secureContext, ...},onconnect_cb)

### CODE REVIEW

**Comment by creationix** [comment]
All ready, use new lit release.

**Comment by rphillips** [comment]
@zhazg is this working for you?

**Comment by zhaozg** [comment]
I think need redo a RP, because not base on master, so I close it.

**Pull request closed without merging**
