### PR TITLE
http: Fix duplication of host/connection/user-agent request headers

### PR DESCRIPTION
**Pull request by squeek502**
Caused when the passed in headers have multiple keys, causing each `found` variable to depend on the iteration order of the headers table (each `found` var would only care about the last header iterated)

Example reproduction:

```lua
    local headers = { {"Front", "test"}, {"Host", "luvit.io"}, {"Behind", "test"} }
    local request = http.request({host="luvit.io", headers=headers})
    request:destroy()
    local num_hosts = 0
    for i,v in ipairs(request) do
      p(i, v)
      if v[1]:lower() == "host" then
        num_hosts = num_hosts + 1
      end
    end
    assert(num_hosts == 1)
```

### CODE REVIEW

**Comment by creationix** [comment]
Good catch.  Can we change the style too.

```lua
if not host_found and klower == 'host' then host_found = value end
```

The `if` should perform better.

**Comment by creationix** [comment]
Since string comparisons are simple pointer comparisons in lua, we can probably remote the `not host_found and` prefix in the condition.  It will change the semantics slightly to match the last matching header instead of the first, but that's fine I think.

**Comment by squeek502** [comment]
Done.

**Comment by creationix** [comment]
Thanks!

**Pull request merged**
