### PR TITLE
Release luvit v2.18.1

### PR DESCRIPTION
**Pull request by creationix**

### CODE REVIEW

**Review by squeek502 — APPROVED** [review]

**Comment by creationix** [comment]
Ok, published to lit and tagged in github.  Was there something else in the release process?  I did write the changelog at least this time.

**Comment by SinisterRectus** [comment]
Not seeing a changelog on the tag...
image

Also if you look at the actual "releases" page (not the tags page), it's still on 2.17.0. https://github.com/luvit/luvit/releases

**Comment by squeek502** [comment]
Made Github releases for 2.18.0 and 2.18.1:
- https://github.com/luvit/luvit/releases/tag/2.18.0
- https://github.com/luvit/luvit/releases/tag/2.18.1

**Comment by SinisterRectus** [comment]
Epic.

**Pull request merged**
