### PR TITLE
converted test from luvit version 1 to 2

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by zhaozg** [comment]
Finished to convert fs test.

**Comment by rphillips** [comment]
The tests/tmp folder does not exist for the `tests/test-fs-truncate.lua` test.

Thanks a bunch!

**Comment by creationix** [comment]
+1

**Comment by creationix** [comment]
If you rebase with master luvit, it should fix the breaking appveyor test.

**Comment by creationix** [comment]
One of the DNS tests seems to be having trouble on OSX.  I wonder if this is related:

```
# Starting Test: dgram-multicast - tls dgram multicast
  'PORT'	10081
  [string "/Users/tim/luvit/tests/test-dgram-multicast.lua"]:40: bad argument #1 to 'addMembership' (invalid option '224.0.0.0')
  stack traceback:
  	[C]: in function 'addMembership'
  	[string "/Users/tim/luvit/tests/test-dgram-multicast.lua"]:40: in function 'fn'
  	[string "/Users/tim/luvit/tests/libs/tap.lua"]:65: in function <[string "/Users/tim/luvit/tests/libs/tap.lua"]:54>
  	[C]: in function 'xpcall'
  	[string "/Users/tim/luvit/tests/libs/tap.lua"]:54: in function 'run'
  	[string "/Users/tim/luvit/tests/libs/tap.lua"]:150: in function 'tap'
  	[string "/Users/tim/luvit/tests/run.lua"]:29: in function 'fn'
  	[string "bundle:deps/require.lua"]:260: in function 'require'
  	[string "bundle:main.lua"]:115: in function 'main'
  	[string "bundle:/init.lua"]:34: in function <[string "bundle:/init.lua"]:32>
  	[C]: in function 'xpcall'
  	[string "bundle:/init.lua"]:32: in function <[string "bundle:/init.lua"]:20>
not ok 11 dgram-multicast - tls dgram multicast
```

**Comment by zhaozg** [comment]
Not sure, need more check for this.

**Comment by rphillips** [comment]
i think we should disable the multicast test (it's not portable, 224.0.0.0 is sometimes restricted in certain environments).

**Comment by zhaozg** [comment]
any one help to test https://gist.github.com/zhaozg/cd1a54e64e1dff61bee6, because I have no mac.

**Comment by creationix** [comment]
I can help on Monday

**Pull request merged**
