### PR TITLE
Add binary extension to search paths

### PR DESCRIPTION
**Pull request by creationix**

### CODE REVIEW

**Comment by rphillips** [comment]
@creationix thoughts on the binary_module/ search path? With my setup, the `modules/sigar.*` got always ignored.

**Comment by creationix** [comment]
On unix binary shared libraries are stored in `lib` folders.  What about using `libs` or `lib` for binary modules.

**Comment by rphillips** [comment]
works for me... i'll fix that up.

**Comment by creationix** [comment]
Actually, I kinda like the idea of having two different folders for searching.  One can be `lib` for libraries statically included (not provided by lit) and the other can be `opt` for where lit puts things.  Lit will exclude `opt` when importing modules, but not `lib`.

What do you think?

**Comment by creationix** [comment]
`opt` contains locally installed software. Originated in System V, which has a package manager that installs software to this directory.

**Comment by creationix** [comment]
Implemented in https://github.com/luvit/lit/commit/6acd8db2c84ac36f7c99bd46ff68ba53b2a2e9bd.  This PR is obsolete.

**Pull request closed without merging**
