### PR TITLE
add http-cookie support

### PR DESCRIPTION
**Pull request by zhaozg**
sometimes, we need build or parse http cookie header for Set-Cookie(response) or Cookie(request),

### CODE REVIEW

**Comment by zhaozg** [comment]
surprise, fail again

**Comment by rphillips** [comment]
i kicked the builds again, since they 503'ed. passes. thanks!

**Comment by creationix** [comment]
How do we want to draw the line between what gets included in core and what lives in lit as a third-party library?

With node, the decision was to draw the line between generic HTTP header parsing/encoding and cookie parsing/encoding.

Luvit is slightly different from node in that it's trivial to make a customized version of luvit with libraries added or removed.  Also building and testing luvit core libraries is no harder than other lit based libraries.  For these reasons there is less chance that a library will go stale once it becomes part of core.

**Comment by zhaozg** [comment]
Sure. It's beter make cookie as lit. Please reset it, I'll try make it as lit package

**Comment by creationix** [comment]
Ok, reset.  So are we deciding that we want to follow the lines node drew for deciding what goes into luvit core?

**Comment by zhaozg** [comment]
Ok, follow the rule

**Pull request merged**
