### PR TITLE
add tostring() on pegmatch

### PR DESCRIPTION
**Pull request by Sezei**
Avoids a few unexpected errors.

### CODE REVIEW

**Comment by Bilal2453** [comment]
Uhhh, I don't know if we should be patching dkjson like this... Worst case scenario is adding couple of type checking

**Comment by Duckwhale** [comment]
It would be good to have a minimale example (or test case) to see what problem this change actually fixes :)

**Comment by Sezei** [comment]
> It would be good to have a minimale example (or test case) to see what problem this change actually fixes :)

A prime example for it would be my discord bot I made not too long ago, [Blueberry](https://github.com/Sezei/Blueberry); For some reason it always responded with "bad argument #2 to 'pegmatch'; expected string, got boolean (or sometimes nil)"; happened with most commands that returned an embed. The commands themselves worked, but just returned the pegmatch error. Modifying my json dep to have tostring(str) solved it instantly.

**Comment by truemedian** [comment]
That error only happens when you're not passing a json string to `json.decode` in the first place. Using `tostring` here will more often than not result in a parsing error anyway because the only thing that will correctly `tostring()` into a valid json payload is `true` and `false`

**Comment by Sezei** [comment]
> That error only happens when you're not passing a json string to `json.decode` in the first place. Using `tostring` here will more often than not result in a parsing error anyway because the only thing that will correctly `tostring()` into a valid json payload is `true` and `false`

As you would probably see in the source code, I do not use any booleans in any if my responses in the first place.

**Pull request closed without merging**
