### PR TITLE
Add luvit thread support

### PR DESCRIPTION
**Pull request by creationix**
Continued from #796

### CODE REVIEW

**Comment by creationix** [comment]
Depends on https://github.com/luvit/luvi/pull/118

**Comment by zhaozg** [comment]
Cool, I will test on windows.

**Comment by zhaozg** [comment]
bug 1, in luvi, luvibundle.lua line 265, on windows pathJoin absolute path

**Comment by zhaozg** [comment]
bug 2, on windows require fail.

```
E:\work\luaclibs\luvit>\work\luabuild\bin\Win32Release\luvit.bat examples\multi-thread-tick.lua

E:\work\luaclibs\luvit>e:\work\luabuild\bin\Win32Release\luvi e:\work\luaclibs\luvit -- examples\multi-thread-tick.lua  
'require'       'E:\\work\\luaclibs\\luvit/examples\\multi-thread-tick.lua'
stack traceback:
        [string "bundle:deps/require.lua"]:267: in function 'require'
        [string "bundle:/main.lua"]:115: in function 'main'
        [string "bundle:/init.lua"]:49: in function <[string "bundle:/init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:/init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:293: in function <[string "bundle:deps/require.lua"]:256>
Uncaught exception:
[string "bundle:deps/require.lua"]:271: No such module 'E:\work\luaclibs\luvit/examples\multi-thread-tick.lua' in 'bundle:/main.lua'
module 'E:\work\luaclibs\luvit/examples\multi-thread-tick.lua' not found:
        no field package.preload['E:\work\luaclibs\luvit/examples\multi-thread-tick.lua']
        no file '.\E:\work\luaclibs\luvit/examples\multi-thread-tick\lua.lua'
        no file 'e:\work\luabuild\bin\Win32Release\lua\E:\work\luaclibs\luvit/examples\multi-thread-tick\lua.lua'
        no file 'e:\work\luabuild\bin\Win32Release\lua\E:\work\luaclibs\luvit/examples\multi-thread-tick\lua\init.lua'
        no file '.\E:\work\luaclibs\luvit/examples\multi-thread-tick\lua.dll'
        no file 'e:\work\luabuild\bin\Win32Release\E:\work\luaclibs\luvit/examples\multi-thread-tick\lua.dll'
        no file 'e:\work\luabuild\bin\Win32Release\loadall.dll'
        no file '.\E:\work\luaclibs\luvit/examples\multi-thread-tick.dll'
        no file 'e:\work\luabuild\bin\Win32Release\E:\work\luaclibs\luvit/examples\multi-thread-tick.dll'
        no file 'e:\work\luabuild\bin\Win32Release\loadall.dll'
stack traceback:
        [C]: in function 'error'
        [string "bundle:deps/require.lua"]:271: in function 'require'
        [string "bundle:/main.lua"]:115: in function 'main'
        [string "bundle:/init.lua"]:49: in function <[string "bundle:/init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:/init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:293: in function <[string "bundle:deps/require.lua"]:256>
```

**Comment by zhaozg** [comment]
luvi.isWindows must be set before require'luvibundle', or luvit will run with unix style path process, 
PR for luvi https://github.com/luvit/luvi/pull/119 solve this bug.

**Comment by zhaozg** [comment]
with same reason, in thread luvi.isWindows must be set before require('luvibundle') , PR of luvit zhaozg-master  https://github.com/luvit/luvit/pull/800

**Comment by zhaozg** [comment]
on windows works fine. +1

**Comment by creationix** [comment]
@zhaozg I fixed the `luvi.isWindows` issue in luvi 2.3.1.  It looks like we're all good now with some minor tweaks to the packaging of luvit itself.

**Comment by rphillips** [comment]
+1

**Comment by zhaozg** [comment]
https://github.com/luvit/luvit/blob/master/deps/thread.lua#L32, should accept  string and function as thread_work, sometimes, we can cache dumped string to save time, dump and dump again.

**Pull request merged**
