### PR TITLE
process: flush stdout on exit

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by creationix** [comment]
So you emit exit first, but don't actually exit till after the flush?

**Comment by rphillips** [comment]
i think that should give anything in the exit handler time to run... what do you think?

**Comment by creationix** [comment]
It does give the exit handler an undetermined time to run.  I fear this will cause more race conditions than anything.

**Comment by rphillips** [comment]
fixed

**Comment by creationix** [comment]
+1

**Comment by creationix** [comment]
Should we do the same thing for stderr?

**Pull request merged**
