### PR TITLE
update changelog and dependencies for a 2.15.0 release

### PR DESCRIPTION
**Pull request by rphillips**
It's been awhile for a release... Update the changelog.

### CODE REVIEW

**Comment by SinisterRectus** [comment]
No 2.15.0?

**Comment by rphillips** [comment]
were there breaking changes to warrant the minor bump?

**Comment by rphillips** [comment]
I don't have a strong preference... I can change it to a 2.15.0.

**Comment by SinisterRectus** [comment]
Is luvit versioned differently than the libs? I thought X was for api breaking, Y for api additions, and Z for internal changes, where the version is X.Y.Z.

**Comment by rphillips** [comment]
You're right... There was a small API addition.

**Comment by zhaozg** [comment]
+1

**Comment by rphillips** [comment]
2.15.0 tagged and released to lit as well.

**Pull request merged**
