### PR TITLE
New Luvit release: 2.17.0

### PR DESCRIPTION
**Pull request by squeek502**
I think we're finally ready to release this. This will be the first Luvit release that specifies a newer Luvi version than 2.7.6 (from Dec 16, 2016!).

---

p.s. This needs to be merged/published to lit at the same time. I'll do that once CI passes/this gets some approvals.

### CODE REVIEW

**Comment by squeek502** [comment]
After running `get-lit.ps1`:

```
>luvit -v
luvit version: 2.17.0
luvi version: v2.10.1
libuv version: 1.34.1
rex version: 8.37 2015-04-28
winsvc version: 1.0.0
ssl version: OpenSSL 1.1.1d  10 Sep 2019, lua-openssl 0.7.7

>lit -v
lit version: 3.8.1
luvi version: v2.10.1

>luvi -v
luvi v2.10.1
libuv: 1.34.1
rex: 8.37 2015-04-28
winsvc: 1.0.0
ssl: OpenSSL 1.1.1d  10 Sep 2019, lua-openssl 0.7.7
```

:tada:

**Comment by SinisterRectus** [comment]
I had hoped we could bump luvi with the miniz fixes before this went out.

**Comment by squeek502** [comment]
I wanted to release this with Luvi 2.10.1 just to get a release that is somewhat known to be 'good.' Now that we have this released, I think we can make more frequent releases. Releasing again with an updated Luv/Luvi sounds good to me.

**Comment by SinisterRectus** [comment]
Alright that sounds fair.

**Pull request merged**
