### PR TITLE
Flush streams on exit (fixes https://github.com/luvit/lit/issues/222)

### PR DESCRIPTION
**Pull request by creationix**

### CODE REVIEW

**Comment by SinisterRectus** [comment]
I was going to say that you could move the `close` callback outside of the `walk` loop and pass `handle` to it instead of creating a new callback with each pass.

**Comment by creationix** [comment]
I could, but then I'd have to create a closure for each stream so that I had the handle to pass to the common close.

I don't think it's a hot path either way.

**Comment by SinisterRectus** [comment]
Or maybe not, if you have to pass the closure to `shutdown`.

**Comment by joerg-krause** [comment]
This PR breaks piping the output of Luvit to a file. See #1083.

**Pull request merged**
