### PR TITLE
Bump lit/luvi versions to latest for testing

### PR DESCRIPTION
**Pull request by squeek502**
This is only for CI purposes. I'll rebase this branch as we fix things, so our goal is to make the CI pass on this branch.

See #1058 & #1060

### CODE REVIEW

**Comment by rphillips** [comment]
Looks like lit may need a lua-openssl tweak.

**Comment by squeek502** [comment]
> Looks like lit may need a lua-openssl tweak.

Yep, needs https://github.com/luvit/lit/pull/257

**Comment by squeek502** [comment]
Published a fixed lit (3.7.3) and rebased to include https://github.com/luvit/luvit/pull/1065

**Comment by zhaozg** [comment]
please rebase on https://github.com/luvit/luvit/pull/1078 and relaunch CI.

**Comment by squeek502** [comment]
Rebased on latest master and merged https://github.com/luvit/luvit/pull/1078 for testing

**Comment by zhaozg** [comment]
The fail narrow
```
Uncaught Error: C:/projects/luvit/tests/test-tls-connect-session-reuse.lua:69: assertion failed!
stack traceback:
	[C]: in function 'assert'
	C:/projects/luvit/tests/test-tls-connect-session-reuse.lua:69: in function 'handler'
	C:/projects/luvit/deps/core.lua:248: in function 'emit'
	C:/projects/luvit/deps/tls/common.lua:238: in function 'handler'
	C:/projects/luvit/deps/core.lua:248: in function 'emit'
	C:/projects/luvit/deps/tls/common.lua:432: in function 'handshake'
	C:/projects/luvit/deps/tls/common.lua:403: in function <C:/projects/luvit/deps/tls/common.lua:392>
	[C]: in function 'run'
	C:/projects/luvit/tests/libs/tap.lua:79: in function <C:/projects/luvit/tests/libs/tap.lua:64>
	[C]: in function 'xpcall'
	C:/projects/luvit/tests/libs/tap.lua:64: in function 'run'
	C:/projects/luvit/tests/libs/tap.lua:165: in function 'tap'
	C:\projects\luvit\tests\run.lua:42: in function 'fn'
	[string "bundle:deps/require.lua"]:310: in function 'require'
	[string "bundle:main.lua"]:118: in function 'main'
	[string "bundle:init.lua"]:49: in function <[string "bundle:init.lua"]:47>
	[C]: in function 'xpcall'
	[string "bundle:init.lua"]:47: in function 'fn'
	[string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
Command exited with code -4
```

**Comment by zhaozg** [comment]
https://github.com/curl/curl/pull/3271 says TLS1.3 session reuse don't same with old version. I wll do some work on it.

**Comment by zhaozg** [comment]
ok 190 tls-connect-session-reuse - tls connect session reuse test on linux/mac
ok 174 tls-connect-session-reuse - tls connect session reuse test on windows

**Comment by squeek502** [comment]
Nice work, rebased on latest master.

**Comment by zhaozg** [comment]
And need to add uv.spawn for windows in luv

**Comment by zhaozg** [comment]
https://github.com/luvit/luv/commit/27a5b5f5b7c131cf02ee1d9fd8085a90bcad6e00 shows uv.spawn works well on windows. https://ci.appveyor.com/project/racker-buildbot/luv/branch/master/job/65mp6f76a96jhf80#L1281

**Comment by rphillips** [comment]
Looks like the test machines may not have enough RAM or swap to run the test:

https://github.com/nodejs/node/issues/25382

**Comment by zhaozg** [comment]
I can do some test on real windows box, in this weekend.

**Comment by zhaozg** [comment]
https://github.com/libuv/libuv/issues/2133

**Comment by squeek502** [comment]
Bumping luv to latest might get all tests to pass now, see https://github.com/luvit/luv/issues/386 for the likely cause of the `ENOMEM` errors on Windows.

**Comment by squeek502** [comment]
I think we've got everything working again :tada:. Not sure why the https-client test failed [here](https://travis-ci.org/luvit/luvit/builds/644089830?utm_source=github_status&utm_medium=notification), but it seems random and I can't reproduce it, so I guess we'll just need to look into it if it becomes a problem.

I'm going to rebase this branch onto latest master for one last test and then we can move forward with a new Luvit release with the latest Luvi.

**Comment by squeek502** [comment]
Closing in favor of https://github.com/luvit/luvit/pull/1098

**Pull request closed without merging**
