### PR TITLE
Release Prep for Luvit v2.18.0

### PR DESCRIPTION
**Pull request by creationix**
- luvi: bump to v2.12.0 [Tim Caswell]
- lit: update to 3.8.5 [Tim Caswell]
- luvit: add the changelog [Tim Caswell]
- Wrap main in a coroutine [@truemedian]

### CODE REVIEW

**Comment by squeek502** [comment]
Are the querystring tests not deterministic?

```
'Expected'	'foo=1&bar=2'
'But got'	'bar=2&foo=1'
  C:/projects/luvit/tests/test-querystring.lua:36: Test #1 failed
```

Weird that we haven't run into this before if so.

**Comment by squeek502** [comment]
Presumably this is from a LuaJIT update between Luvi 2.10.1 and 2.12.0. The querystring tests are probably erroneously relying on table pairs iteration order.

**Review by squeek502 — DISMISSED** [review]
Should be good, CI failure can be fixed by https://github.com/luvit/luvit/pull/1143

**Comment by creationix** [comment]
I rebased after merging your test fix.  But now it wants another review.

**Review by squeek502 — APPROVED** [review]

**Comment by creationix** [comment]
Should I worry about this?
```
# Starting Test: colors - Recursive values
  recursive	{ data = table: 0x0348cfd0, a = 'value' }	"{ data = table: 0x0348cfd0, a = 'value' }"
  C:/projects/luvit/tests/test-colors.lua:31: assertion failed!
  stack traceback:
  	[C]: in function 'assert'
  	C:/projects/luvit/tests/test-colors.lua:31: in function 'fn'
  	C:/projects/luvit/tests/libs/tap.lua:77: in function <C:/projects/luvit/tests/libs/tap.lua:64>
  	[C]: in function 'xpcall'
  	C:/projects/luvit/tests/libs/tap.lua:64: in function 'run'
  	C:/projects/luvit/tests/libs/tap.lua:165: in function 'tap'
  	C:\projects\luvit\tests\run.lua:42: in function 'fn'
  	[string "bundle:deps/require.lua"]:310: in function 'require'
  	[string "bundle:/main.lua"]:128: in function <[string "bundle:/main.lua"]:20>
not ok 2 colors - Recursive values
```

**Comment by squeek502** [comment]
More reliance on iteration order. Looks like Luvit was inadvertently expecting consistent iteration order a lot. Looks like the test can be fixed without updating `utils`, same as the `test-querystring` case.

**Comment by squeek502** [comment]
https://github.com/luvit/luvit/pull/1144

**Comment by creationix** [comment]
This test was a little harder to fix.  I can't parse the table reference since it's not valid lua.  So I just removed the extra value so that the recursive part is always in the same spot.

**Comment by squeek502** [comment]
Ah, yeah, that works too.

**Review by squeek502 — APPROVED** [review]

**Comment by creationix** [comment]
I guess I could have also done this:

```lua
    assert(string.match(stripped, "{ a = 'value', data = table: 0x%x+ }")
        or string.match(stripped, "{ data = table: 0x%x+, a = 'value' }"))
```

**Comment by squeek502** [comment]
I'm actually getting local failures on Linux that look real. Since `travis-ci.org` is dead, we're not running Linux/Mac CI right now. We might want to hold off on this release for a bit.

One error I'm getting (which is skipped on Windows so its not failing the CI):

```
# Starting Test: tls-server-verify - Do not request certs. Everyone is unauthorized.
    connecting with agent1
'openssls_client -tls1 -connect 127.0.0.1:32000 -key /home/ryan/Programming/luvit/luvit/tests/fixtures/keys/agent1-key.pem -cert /home/ryan/Programming/luvit/luvit/tests/fixtures/keys/agent1-cert.pem'
  - unauthed connection: undefined
Uncaught Error: ...Programming/luvit/luvit/tests/test-tls-server-verify.lua:111: agent1 rejected, but should NOT have been
stack traceback:
	[C]: in function 'assert'
	...Programming/luvit/luvit/tests/test-tls-server-verify.lua:111: in function 'handler'
	/home/ryan/Programming/luvit/luvit/deps/core.lua:248: in function 'emit'
	/home/ryan/Programming/luvit/luvit/deps/childprocess.lua:128: in function </home/ryan/Programming/luvit/luvit/deps/childprocess.lua:125>
	[C]: in function 'run'
	/home/ryan/Programming/luvit/luvit/tests/libs/tap.lua:79: in function </home/ryan/Programming/luvit/luvit/tests/libs/tap.lua:64>
	[C]: in function 'xpcall'
	/home/ryan/Programming/luvit/luvit/tests/libs/tap.lua:64: in function 'run'
	/home/ryan/Programming/luvit/luvit/tests/libs/tap.lua:165: in function 'tap'
	/home/ryan/Programming/luvit/luvit/tests/run.lua:42: in function 'fn'
	[string "bundle:deps/require.lua"]:310: in function 'require'
	/home/ryan/Programming/luvit/luvit/main.lua:128: in function 'main'
	/home/ryan/Programming/luvit/luvit/init.lua:49: in function </home/ryan/Programming/luvit/luvit/init.lua:47>
	[C]: in function 'xpcall'
	/home/ryan/Programming/luvit/luvit/init.lua:47: in function 'fn'
	[string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```

**Comment by creationix** [comment]
Yep.  We can continue another day.


image

**Comment by squeek502** [comment]
I'll work on getting Linux/Mac CI set up again; Luvit's is pretty simple so it shouldn't be too hard.

**Comment by creationix** [comment]
Is there a way to rebase on master?

**Comment by squeek502** [comment]
Don't think so, but looks like there's one more test that needs fixing on Linux: https://github.com/luvit/luvit/issues/1148

**Review by squeek502 — APPROVED** [review]

**Pull request merged**
