### PR TITLE
green Ci

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by zhaozg** [comment]
https://lit.luvit.io/ failed to download something, need check

**Comment by creationix** [comment]
Looks great.  The lit.luvit.io server was down, but I fixed it.

**Comment by creationix** [comment]
I restarted the builds, let's see if that helps.

**Comment by SinisterRectus** [comment]
Looks good from here. Just needs a version bump and release.

**Comment by SinisterRectus** [comment]
Apparently when I successfully tested this on Windows, I was running `luvit.exe` from the luvit directory, which had a `deps` folder in it. If I try to run the executable elsewhere, the standard luvit modules still fail to load. I assume that it was previously loading them from the `deps` folder instead of the bundle.

Can someone else please test this on Windows?

**Comment by creationix** [comment]
Sorry, I'm out of town and don't have a windows machine with me.  Hopefully someone else can test it.

**Comment by squeek502** [comment]
Getting the same thing as @SinisterRectus.

```
C:\Users\Ryan\Programming\Luvit>luvit.exe
Welcome to the Luvit repl!
> [string "bundle:deps/require.lua"]:279: No such module 'buffer' in 'C:/Users/Ryan/Programming/Luvit/repl'
module 'buffer' not found:
        no field package.preload['buffer']
        no file '.\buffer.lua'
        no file 'C:\Users\Ryan\Programming\Luvit\lua\buffer.lua'
        no file 'C:\Users\Ryan\Programming\Luvit\lua\buffer\init.lua'
        no file '.\buffer.dll'
        no file 'C:\Users\Ryan\Programming\Luvit\buffer.dll'
        no file 'C:\Users\Ryan\Programming\Luvit\loadall.dll'
stack traceback:
        [C]: in function 'error'
        [string "bundle:deps/require.lua"]:279: in function 'require'
        [string "REPL"]:1: in main chunk
        [C]: in function 'xpcall'
        [string "bundle:deps/repl.lua"]:93: in function 'evaluateLine'
        [string "bundle:deps/repl.lua"]:197: in function <[string "bundle:deps/repl.lua"]:194>
        [builtin:foreach]: in function 'foreach'
        [string "bundle:deps/repl.lua"]:194: in function 'start'
        [string "bundle:main.lua"]:137: in function 'main'
        [string "bundle:init.lua"]:49: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
[string "bundle:deps/require.lua"]:279: No such module 'childprocess' in 'C:/Users/Ryan/Programming/Luvit/repl'
module 'childprocess' not found:
...
...
...
(these errors go on for a while)
```

Note, though, that some other things still work (`luvit -v`, `luvit -h`, `luvit -e "p('test')"`), so it looks specific to `repl` somehow?

**Comment by squeek502** [comment]
Should be fixed once #977 is merged.

**Comment by creationix** [comment]
Thanks @squeek502!

**Pull request merged**
