### PR TITLE
fix tests/test-http-post-1mb.lua to pass

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by rphillips** [comment]
+1

**Comment by zhaozg** [comment]
Strange, why I test fail with luvit master, but https://travis-ci.org/luvit/luvit and https://ci.appveyor.com/project/racker-buildbot/luvit/branch/master pass for http-post-1mb.lua

**Comment by zhaozg** [comment]
https://travis-ci.org/luvit/luvit/builds/60535507#L880-L885, a peice of chunk is 1048576, 
But on my PC, a few peices of chunk to get right result.

**Comment by zhaozg** [comment]
image

**Comment by rphillips** [comment]
ok. try pulling... the expect() call on the data event was not correct.

https://github.com/luvit/luvit/commit/07f4735150204d3defee50f774049f21a8acda0d

**Comment by zhaozg** [comment]
verified.

**Pull request merged**
