### PR TITLE
bump files for 2.11.2

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by creationix** [comment]
Hmm, I thought I did a release the other day with some of this.  Did I forget to push to github?

**Comment by rphillips** [comment]
perhaps, I don't see a tag

**Comment by creationix** [comment]
No idea what happened, my local checkout matches master.  But I did publish it to lit, so 2.11.1 is already taken and we need to bump the version again.

**Comment by creationix** [comment]
+1

**Pull request merged**
