### PR TITLE
feat(spawn): add close event when all stdio are closed

### PR DESCRIPTION
**Pull request by rphillips**
See: https://nodejs.org/api/child_process.html#child_process_event_close

### CODE REVIEW

**Comment by rphillips** [comment]
cc/ @kaustavha

**Comment by rphillips** [comment]
Example: https://gist.github.com/rphillips/70868e105d12aa80aece

**Comment by creationix** [comment]
Looks good. +1

**Comment by kaustavha** [comment]
Nice

**Pull request merged**
