### PR TITLE
converted test from version 1 to 2

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by creationix** [comment]
I love the fixes, updates and new tests.  Any idea why one test is hanging on travis?

**Comment by zhaozg** [comment]
please update luvi,build with last lua-openssl will support SNI

**Comment by zhaozg** [comment]
> Any idea why one test is hanging on travis?

Have no idea, and that's strange

**Comment by rphillips** [comment]
I don't recall implementing SNI support, so skipping that test is fine.

**Comment by rphillips** [comment]
+1

**Comment by zhaozg** [comment]
Hanging on travis has been fixed, because not close socket.
And test-tls-sni-server-client.lua should be work after lit use luvi next version"2.0.7".
All test done.

**Pull request merged**
